# Generated by Django 4.2.4 on 2024-07-18 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apl01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
